private-key-encrypted: "OwWrEtDWl7mq79FM-mb4hbrU9uBtffvX3MPuEjcXenWocH-JS4SVYXFr0rm-wYuWHnwrzLYvatKGywShwMVCEZw6f-g2XyDIPdrEzAHCZ8WH_v76kJsVEOGEe8qRvy4z6ai0YGFpzV4iFB8NfZEg5kb9k88"
promotion-comment: "<h6>If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>"

evm-network-id: 100
price-multiplier: 1
issue-creator-multiplier: 4
max-concurrent-assigns: 2
payment-permit-max-price: 1000

disable-analytics: true
comment-incentives: true
assistive-pricing: true
register-wallet-with-verification: false

time-labels:
  - name: "Time: <1 Hour"
    weight: 0.125
    value: 3600
  - name: "Time: <2 Hours"
    weight: 0.25
    value: 7200
  - name: "Time: <4 Hours"
    weight: 0.5
    value: 14400
  - name: "Time: <1 Day"
    weight: 1
    value: 86400
  - name: "Time: <1 Week"
    weight: 2
    value: 604800

priority-labels:
  - name: "Priority: 1 (Normal)"
    weight: 1
  - name: "Priority: 2 (Medium)"
    weight: 2
  - name: "Priority: 3 (High)"
    weight: 3
  - name: "Priority: 4 (Urgent)"
    weight: 4
  - name: "Priority: 5 (Emergency)"
    weight: 5

incentives:
  comment:
    elements:
      code: 1
      img: 0
      h1: 1
      h2: 1
      h3: 1
      h4: 1
      h5: 1
      h6: 1
      li: 0.5
      a: 1
      blockquote: 0
      i: 0
    totals:
      word: 0.1

command-settings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: payout
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: allow
    enabled: true
  - name: autopay
    enabled: true

enable-access-control:
  label: true
  organization: true
