name: Delegated Compute Workflow
#get log & tags information
on:
  workflow_dispatch:
    inputs:
      eventName:
        description: "name of the received event"
        required: true
      organization:
        description: "name of the organization"
        required: true
      issueOwner:
        description: "name of the owner of organization"
        required: true
      issueRepository:
        description: "name of the repo"
        required: true
      issueNumber:
        description: "issue Number of the event"
        required: true
      repoCollaborators:
        description: "repository collaborators"
        required: true

jobs:
  handler-job:
    runs-on: ubuntu-latest
    steps:
      - name: print event name
        run: echo ${{ inputs.eventName }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
      - name: Calling action
        uses: ./ # Uses an action in the root directory
        id: callback
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          X25519_PRIVATE_KEY: ${{ secrets.X25519_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Debug log values
        run: |
          echo "Inputs: ${{ toJson(inputs) }}"
          echo "github.repository: ${{ toJson(github.repository) }}"

      - name: Trigger repository_dispatch to the repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"${{ inputs.eventName }}","client_payload":{"result": ${{ steps.callback.outputs.result }}, "issueNumber":"${{ inputs.issueNumber }}", "issueOwner":"${{ inputs.issueOwner }}", "issueRepository":"${{ inputs.issueRepository }}"}}'
